### ISSUE TITLE
example-etcd-cluster not created

### ISSUE THREAD

**Issue by itsbanjo** [kubernetes-operators-book/chapters#6]
upon running oc create -f etcd-cluster-cr.yaml the example-etcd-cluster-* pods are not created

**Comment by 0xdnL** [comment]
same for `kubectl create -f etcd-cluster-cr.yaml` which throws

```
error: error validating "etcd-cluster-cr.yaml": error validating data: [ValidationError(EtcdCluster.spec): 
unknown field "size" in com.coreos.database.etcd.v1.EtcdCluster.spec, ValidationError(EtcdCluster.spec): 
unknown field "version" in com.coreos.database.etcd.v1.EtcdCluster.spec]; 
if you choose to ignore these errors, turn validation off with --validate=false
```

using `--validate=false` doesn't change anything

minikube version: `v1.23.2`
kubernets server: `1.22+`

the versions I use also have changes for `apiextensions.k8s.io/v1` which I was able to fix by changing the spec
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#customresourcedefinition-v122

but `kubectl create -f etcd-cluster-cr.yaml` won't bring up pods

@joshix @jdob will you update the example for later versions of the k8s-api ?

**Comment by 0xdnL** [comment]
ok, I fixed the validation by using this schema (which has become required in `apiextensions.k8s.io/v1` )

```
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              size:
                type: integer
              version:
                type: string
```

now one pod is tries to start:

```
example-etcd-cluster-cfvbzv546g   0/1     Init:0/1   0          15m
```

but the init-container throws:
```
kubectl logs example-etcd-cluster-cfvbzv546g -c check-dns

nslookup: can't resolve 'example-etcd-cluster-cfvbzv546g.example-etcd-cluster.default.svc'
nslookup: can't resolve 'example-etcd-cluster-cfvbzv546g.example-etcd-cluster.default.svc'
Server:    10.96.0.10
Address 1: 10.96.0.10 kube-dns.kube-system.svc.cluster.local
...
```
